### ISSUE TITLE
Missing dependency: pip3 install --user pysrt

### ISSUE THREAD

**Issue by sevospl** [FraMecca/subtitle_cleaner#1]
I tried both global installing this module and manual as well (inside a virtual environment) but it seems to not detect it. Any idea how to solve it?

**Comment by FraMecca** [comment]
I updated the readme with more details on dependencies and installation.

The script depends on chardet and pysrt. Do you have them installed?

Can you provide me with the output that results from running the script?

**Comment by sevospl** [comment]
Following the added instructions it worked out well but when trying to use a specific Python script (subscleaner ) with a fixed path it still seems to complain about the dependencies. When using just a command (without any path) it works okay.

However, I analyzed all SRTs and most of them have "OpenSubtitles" included - they're not removed.

**Comment by FraMecca** [comment]
Can you give me an example of a run?

Also, regarding the advertisement of OpenSubtitles, can you send me by email or embed here a srt file? Signature for advertisements need to be added manually in form of regex here:
https://github.com/FraMecca/subscleaner/blob/be8bbc4b09a1f3f9a664eb101d3d481ec86bac4a/subscleaner#L16

**Comment by sevospl** [comment]
SRT files sent :) There was no output whatsoever, it literally just analyzed the files and then got quiet about anything.

**Comment by FraMecca** [comment]
I pushed a new commit to the repo.
Close the issue if the results match your expectations.
